# Generated by Django 4.1.4 on 2023-01-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
